name: flutter_application
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "asset/icons/icon.png"
  android: true
  ios: true
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  provider: ^5.0.0
  path_provider: ^2.0.2
  image_picker: ^0.7.0
  flutter_svg: ^0.20.0-nullsafety.3
  intl: ^0.17.0
  http: ^0.13.0
  shared_preferences: ^2.0.1
  cupertino_icons: ^1.0.0
  firebase_storage: ^8.0.0
  convex_bottom_bar: ^3.0.0
  firebase_database: ^6.1.0
  adaptive_theme: ^2.0.0
  image_picker_for_web: ^2.0.0
  firebase_auth: ^1.0.2
  firebase_auth_web: ^1.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  toast: ^0.1.5
  timeago: ^3.1.0
  random_string: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_launcher_icons: ^0.9.0
  dcdg: ^3.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: Nexa
      fonts:
        - asset: asset/fonts/Nexa_Bold.otf
        - asset: asset/fonts/Nexa_Light.otf

  assets:
     - asset/icons/

